# Generated by Django 5.0.3 on 2026-02-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemedialClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('remedial_code', models.CharField(max_length=10, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.campusfaculty')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.campusclassroom')),
            ],
        ),
        migrations.CreateModel(
            name='RemedialAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
                ('remedial_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remedial.remedialclass')),
            ],
            options={
                'unique_together': {('remedial_class', 'student')},
            },
        ),
    ]
