# Generated by Django 4.2 on 2026-02-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_campusfaculty_options_campusfaculty_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='campusclassroom',
            options={'ordering': ['block__name', 'room_number']},
        ),
        migrations.AlterModelOptions(
            name='campusfaculty',
            options={'ordering': ['name'], 'verbose_name_plural': 'Campus Faculty'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='campusclassroom',
            name='room_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='campusfaculty',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='campusfaculty',
            name='faculty_id',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='campusfaculty',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='classroomschedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='resources.campusclassroom'),
        ),
        migrations.AlterField(
            model_name='classroomschedule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_schedules', to='resources.event'),
        ),
        migrations.AlterField(
            model_name='course',
            name='assigned_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='resources.campusfaculty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='campusclassroom',
            index=models.Index(fields=['block', 'room_number'], name='resources_c_block_i_3e3a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='campusfaculty',
            index=models.Index(fields=['email'], name='resources_c_email_fb3d24_idx'),
        ),
        migrations.AddIndex(
            model_name='campusfaculty',
            index=models.Index(fields=['faculty_id'], name='resources_c_faculty_f84417_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomschedule',
            index=models.Index(fields=['classroom', 'event'], name='resources_c_classro_94fe4d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['assigned_faculty'], name='resources_c_assigne_7601d9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time', 'end_time'], name='resources_e_start_t_560691_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-start_time'], name='resources_e_start_t_f45bf8_idx'),
        ),
    ]
