# Generated by Django 4.2 on 2026-02-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_fooditem_options_alter_foodorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('desserts', 'Desserts')], db_index=True, default='snacks', max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='time_slot',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['stall', 'available'], name='food_foodit_stall_i_12b4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['category', 'available'], name='food_foodit_categor_e16d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['stall', 'status'], name='food_foodor_stall_i_cf81aa_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['user', '-time_slot'], name='food_foodor_user_id_adc042_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['-time_slot', 'status'], name='food_foodor_time_sl_c9f89a_idx'),
        ),
        migrations.AddIndex(
            model_name='foodstall',
            index=models.Index(fields=['vendor', 'is_active'], name='food_foodst_vendor__128c15_idx'),
        ),
    ]
