# Generated by Django 4.2 on 2026-02-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_fooditem_available_alter_fooditem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('qr', 'QR Code/UPI')], default='cod', max_length=10),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='foodstall',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='UPI QR Code for payments', null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='foodstall',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for generating QR code', max_length=100, null=True),
        ),
    ]
