# Generated by Django 4.2 on 2026-02-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodorder_payment_method_foodorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('qr', 'UPI/QR Code Payment'), ('card', 'Debit/Credit Card'), ('wallet', 'Campus Wallet')], default='cod', max_length=10),
        ),
    ]
