# Generated by Django 4.2 on 2026-02-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_foodorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstall',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='foodstall',
            name='email',
            field=models.EmailField(blank=True, help_text='Stall email address for order notifications', max_length=255, null=True),
        ),
    ]
