# Generated by Django 4.2 on 2026-02-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], db_index=True, default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'status'], name='attendance__student_cb2706_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_date', 'status'], name='attendance__class_d_299d38_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['-class_date'], name='attendance__class_d_ef576b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='attendance__name_d95c02_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='attendance__student_40cee0_idx'),
        ),
    ]
