# Generated by Django 4.2 on 2026-02-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_block_options_alter_campusclassroom_options_and_more'),
        ('attendance', '0003_alter_attendance_class_date_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'faculty', 'course', 'class_date', 'class_time')},
        ),
    ]
